language: node_js
node_js:
    - "0.10"
    - "0.12"
    - iojs
before_install: npm install -g grunt-cli
install: npm install
services:
    - mongodb
after_script: "npm install coveralls && cat ./lcov.info | coveralls"